In [4]:
import pandas as pd

In [5]:
data_frame = pd.read_csv("../data/Salaries.csv")
data_frame

yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
25570    2015    WAS   NL  treinbl01    512800
25571    2015    WAS   NL  ugglada01    507500
25572    2015    WAS   NL  werthja01  21000000
25573    2015    WAS   NL  zimmejo02  16500000
25574    2015    WAS   NL  zimmery01  14000000

[25575 rows x 5 columns]

In [6]:
data_frame.set_index('playerID')

yearID teamID lgID    salary
playerID                               
barkele01    1985    ATL   NL    870000
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25575 rows x 4 columns]

In [7]:
data_frame.columns = data_frame.iloc[0]
data_frame = data_frame[1:]
data_frame.head()

0  1985  ATL  NL  barkele01  870000
1  1985  ATL  NL  bedrost01  550000
2  1985  ATL  NL  benedbr01  545000
3  1985  ATL  NL   campri01  633333
4  1985  ATL  NL  ceronri01  625000
5  1985  ATL  NL  chambch01  800000

In [47]:
data_frame_copy = pd.read_csv('../data/Salaries.csv')
data_frame_copy

yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
25570    2015    WAS   NL  treinbl01    512800
25571    2015    WAS   NL  ugglada01    507500
25572    2015    WAS   NL  werthja01  21000000
25573    2015    WAS   NL  zimmejo02  16500000
25574    2015    WAS   NL  zimmery01  14000000

[25575 rows x 5 columns]

In [48]:
rows = data_frame_copy.loc[((data_frame_copy['teamID'] == 'ATL') | (data_frame_copy['teamID'] == 'HOU')) & (data_frame_copy['salary']>1000000)]
rows

yearID teamID lgID   playerID   salary
10       1985    ATL   NL  hornebo01  1500000
15       1985    ATL   NL  murphda05  1625000
20       1985    ATL   NL  suttebr01  1354167
216      1985    HOU   NL   ryanno01  1350000
559      1986    ATL   NL  hornebo01  1800000
...       ...    ...  ...        ...      ...
25053    2015    HOU   AL  quallch01  3000000
25054    2015    HOU   AL  rasmuco01  8000000
25055    2015    HOU   AL  singljo02  2000000
25056    2015    HOU   AL   sippto01  2400000
25059    2015    HOU   AL  valbulu01  4200000

[595 rows x 5 columns]

In [49]:
atl_rows = data_frame_copy[data_frame_copy['teamID'] == 'ATL']
atl_rows.describe()

yearID        salary
count   886.000000  8.860000e+02
mean   1999.708804  2.206239e+06
std       8.775471  3.432673e+06
min    1985.000000  6.000000e+04
25%    1992.000000  3.000000e+05
50%    1999.000000  6.000000e+05
75%    2007.000000  2.390625e+06
max    2015.000000  1.606180e+07

In [50]:
keys = data_frame_copy.columns
keys

Index(['yearID', 'teamID', 'lgID', 'playerID', 'salary'], dtype='object')

In [51]:
dictionary = {};
for key_name in keys:
    dictionary[key_name] = [];

In [52]:
dictionary

{'yearID': [], 'teamID': [], 'lgID': [], 'playerID': [], 'salary': []}

In [53]:
key_dictionary = {};
for key_name in keys:
    for index, row_data in data_frame_copy.iterrows():
        key_dictionary[index] = row_data[key_name];
    dictionary[key_name] = key_dictionary;
    key_dictionary = {};
dictionary

{'yearID': {0: 1985,
  1: 1985,
  2: 1985,
  3: 1985,
  4: 1985,
  5: 1985,
  6: 1985,
  7: 1985,
  8: 1985,
  9: 1985,
  10: 1985,
  11: 1985,
  12: 1985,
  13: 1985,
  14: 1985,
  15: 1985,
  16: 1985,
  17: 1985,
  18: 1985,
  19: 1985,
  20: 1985,
  21: 1985,
  22: 1985,
  23: 1985,
  24: 1985,
  25: 1985,
  26: 1985,
  27: 1985,
  28: 1985,
  29: 1985,
  30: 1985,
  31: 1985,
  32: 1985,
  33: 1985,
  34: 1985,
  35: 1985,
  36: 1985,
  37: 1985,
  38: 1985,
  39: 1985,
  40: 1985,
  41: 1985,
  42: 1985,
  43: 1985,
  44: 1985,
  45: 1985,
  46: 1985,
  47: 1985,
  48: 1985,
  49: 1985,
  50: 1985,
  51: 1985,
  52: 1985,
  53: 1985,
  54: 1985,
  55: 1985,
  56: 1985,
  57: 1985,
  58: 1985,
  59: 1985,
  60: 1985,
  61: 1985,
  62: 1985,
  63: 1985,
  64: 1985,
  65: 1985,
  66: 1985,
  67: 1985,
  68: 1985,
  69: 1985,
  70: 1985,
  71: 1985,
  72: 1985,
  73: 1985,
  74: 1985,
  75: 1985,
  76: 1985,
  77: 1985,
  78: 1985,
  79: 1985,
  80: 1985,
  81: 1985,
  82: 1985,
  83

In [56]:
new_data_frame = pd.DataFrame(dictionary)

In [57]:
new_data_frame = new_data_frame.rename(columns={'yearID': 'a', 'teamID': 'b', 'lgID': 'c', 'playerID': 'd', 'salary': 'e'})

In [58]:
new_data_frame

a    b   c          d         e
0      1985  ATL  NL  barkele01    870000
1      1985  ATL  NL  bedrost01    550000
2      1985  ATL  NL  benedbr01    545000
3      1985  ATL  NL   campri01    633333
4      1985  ATL  NL  ceronri01    625000
...     ...  ...  ..        ...       ...
25570  2015  WAS  NL  treinbl01    512800
25571  2015  WAS  NL  ugglada01    507500
25572  2015  WAS  NL  werthja01  21000000
25573  2015  WAS  NL  zimmejo02  16500000
25574  2015  WAS  NL  zimmery01  14000000

[25575 rows x 5 columns]

In [60]:
import numpy as np

In [66]:
list = [['Apple', 'Orange', 'Carrot'], ['Soccer', 'Football', 'Hockey'], ['Pant', 'Shirt', 'Skirt']]

In [67]:
np_array = np.array(list)
np_array

array([['Apple', 'Orange', 'Carrot'],
       ['Soccer', 'Football', 'Hockey'],
       ['Pant', 'Shirt', 'Skirt']], dtype='<U8')

In [68]:
np_array.ndim

2

In [69]:
np_array.shape

(3, 3)

In [70]:
np_array.size

9

In [71]:
np_array.dtype

dtype('<U8')

In [72]:
np_array.itemsize

32

In [73]:
np_array.data

In [74]:
np_array.flatten()

array(['Apple', 'Orange', 'Carrot', 'Soccer', 'Football', 'Hockey',
       'Pant', 'Shirt', 'Skirt'], dtype='<U8')

In [75]:
np.reshape(np_array, (3,3))

array([['Apple', 'Orange', 'Carrot'],
       ['Soccer', 'Football', 'Hockey'],
       ['Pant', 'Shirt', 'Skirt']], dtype='<U8')

In [77]:
np_array[1:2,2]

array(['Hockey'], dtype='<U8')

In [78]:
np_array[0:2, 0:1]

array([['Apple'],
       ['Soccer']], dtype='<U8')

In [83]:
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [84]:
a.argmin()

0

In [85]:
a.argmin(axis =0)

array([0, 0, 0], dtype=int64)

In [87]:
a.argmin(axis = 1)

array([0, 0], dtype=int64)

In [88]:
a.argmax()

5

In [89]:
a.argmax(axis = 1)

array([2, 2], dtype=int64)

In [90]:
a.min()

10

In [91]:
a.max()

15

In [92]:
a.mean()

12.5

In [93]:
a.sum()

75

In [94]:
a.std()

1.707825127659933

In [100]:
b = np.arange(6).reshape(3,2) + 10
b

array([[10, 11],
       [12, 13],
       [14, 15]])

In [101]:
np.dot(a,b)

array([[400, 433],
       [508, 550]])

In [103]:
np.square(a)

array([[100, 121, 144],
       [169, 196, 225]], dtype=int32)

In [104]:
np.sqrt(a)

array([[3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335]])

In [105]:
np.abs(a)

array([[10, 11, 12],
       [13, 14, 15]])

In [106]:
np.exp(a)

array([[  22026.46579481,   59874.1417152 ,  162754.791419  ],
       [ 442413.39200892, 1202604.28416478, 3269017.37247211]])

In [107]:
np.sign(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [109]:
np.mod(a, 4)

array([[2, 3, 0],
       [1, 2, 3]], dtype=int32)

In [112]:
np.arange(0,5,1, dtype=int)

array([0, 1, 2, 3, 4])

In [113]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [115]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
np.eye(6,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.linspace(5, 100, num=10)

array([  5.        ,  15.55555556,  26.11111111,  36.66666667,
        47.22222222,  57.77777778,  68.33333333,  78.88888889,
        89.44444444, 100.        ])

In [119]:
np.linspace(5, 100, num=10, endpoint=True, retstep =True)

(array([  5.        ,  15.55555556,  26.11111111,  36.66666667,
         47.22222222,  57.77777778,  68.33333333,  78.88888889,
         89.44444444, 100.        ]),
 10.555555555555555)

In [120]:
arr1 = np.array(['a', 'b'])

In [121]:
arr2 = np.array(['c', 'd'])

In [123]:
np.concatenate((arr1,arr2), axis = 0)

array(['a', 'b', 'c', 'd'], dtype='<U1')